"""
Builds the single asset the deployed app needs (app/assets/diabetic_data_features.csv)
from the full local pipeline output in data/processed/ (gitignored — regenerated by
the notebooks/src scripts).

Why this exists: data/processed/ is intentionally not committed (see
data/README.md), but Streamlit Community Cloud only has whatever's in the
GitHub repo — no local pipeline run. The app trains fresh from this CSV at
startup (see app/streamlit_app.py) rather than unpickling pre-fit models,
since fitted sklearn/xgboost objects aren't guaranteed compatible across
library versions and a deploy environment can resolve a newer scikit-learn
than whatever trained the pickle. Trimmed to just the columns models.py and
the fairness audit actually use, not the full 62-column feature table.

Run locally after regenerating data/processed/diabetic_data_features.csv:
`python app/prepare_assets.py`, then commit app/assets/.
"""
from pathlib import Path

import pandas as pd

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from models import NUMERIC_FEATURES, CATEGORICAL_FEATURES, TARGET_COL, GROUP_COL  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "app" / "assets"

AUDIT_ONLY_COLUMNS = ["race", "gender", "age"]


def main():
    ASSETS.mkdir(exist_ok=True)
    df = pd.read_csv(ROOT / "data/processed/diabetic_data_features.csv")

    keep_cols = list(dict.fromkeys(
        NUMERIC_FEATURES + CATEGORICAL_FEATURES + [TARGET_COL, GROUP_COL] + AUDIT_ONLY_COLUMNS
    ))
    trimmed = df[keep_cols]
    out_path = ASSETS / "diabetic_data_features.csv"
    trimmed.to_csv(out_path, index=False)

    print(f"Wrote {out_path}: {trimmed.shape}, {out_path.stat().st_size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
