"""
Builds the small, self-contained asset bundle the deployed Streamlit app
actually needs (app/assets/), from the full local pipeline output in
data/processed/ (gitignored — regenerated by the notebooks/src scripts).

Why this exists: data/processed/ is intentionally not committed (see
data/README.md), but Streamlit Community Cloud only has whatever's in the
GitHub repo — no local pipeline run. Rather than committing the full
pipeline output (splits.joblib alone is 28MB because it carries X_train too,
which the app never uses), this trims to exactly what app/streamlit_app.py
reads: the 3 fitted models, the test split only, and just the 3 demographic
columns the Fairness tab needs (not the full 62-column feature table).

Run locally after retraining: `python app/prepare_assets.py`, then commit
app/assets/.
"""
import shutil
from pathlib import Path

import joblib
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "app" / "assets"


def main():
    ASSETS.mkdir(exist_ok=True)

    for name in ["logistic_regression", "random_forest", "xgboost"]:
        shutil.copy(ROOT / f"data/processed/models/{name}.joblib", ASSETS / f"{name}.joblib")

    _, X_test, _, y_test = joblib.load(ROOT / "data/processed/models/splits.joblib")
    joblib.dump((X_test, y_test), ASSETS / "test_split.joblib")

    features_df = pd.read_csv(ROOT / "data/processed/diabetic_data_features.csv")
    demo = features_df.loc[X_test.index, ["race", "gender", "age"]]
    demo.to_csv(ASSETS / "demo_subset.csv")

    print("Wrote app/assets/:")
    for f in sorted(ASSETS.iterdir()):
        print(f"  {f.name}: {f.stat().st_size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
